-- MySQL Script generated by MySQL Workbench
-- Sun Feb  7 23:55:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema play_my_beat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema play_my_beat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `play_my_beat` DEFAULT CHARACTER SET utf8 ;
USE `play_my_beat` ;

-- -----------------------------------------------------
-- Table `play_my_beat`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `play_my_beat`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `play_my_beat`.`runs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `play_my_beat`.`runs` (
  `user_id` INT NOT NULL,
  `run_id` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATETIME NOT NULL,
  `start_date_nano` BIGINT NOT NULL,
  `end_date` DATETIME NOT NULL,
  `end_date_nano` BIGINT NOT NULL,
  PRIMARY KEY (`run_id`),
  UNIQUE INDEX `run_id_UNIQUE` (`run_id` ASC) VISIBLE,
  INDEX `fk_runs_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_runs_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `play_my_beat`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `play_my_beat`.`heart_rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `play_my_beat`.`heart_rate` (
  `run_id` INT NOT NULL,
  `reg_id` INT NOT NULL AUTO_INCREMENT,
  `run_min` TIME NOT NULL,
  `bpm` INT NOT NULL,
  PRIMARY KEY (`reg_id`),
  INDEX `fk_heart_rate_runs1_idx` (`run_id` ASC) VISIBLE,
  CONSTRAINT `fk_heart_rate_runs1`
    FOREIGN KEY (`run_id`)
    REFERENCES `play_my_beat`.`runs` (`run_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `play_my_beat`.`other data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `play_my_beat`.`other data` (
  `run_id` INT NOT NULL,
  `reg_id` INT NOT NULL AUTO_INCREMENT,
  `distance` INT NOT NULL,
  `steps` INT NOT NULL,
  `calories` INT NOT NULL,
  PRIMARY KEY (`reg_id`),
  INDEX `fk_other data_runs1_idx` (`run_id` ASC) VISIBLE,
  CONSTRAINT `fk_other data_runs1`
    FOREIGN KEY (`run_id`)
    REFERENCES `play_my_beat`.`runs` (`run_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `play_my_beat`.`google_secrets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `play_my_beat`.`google_secrets` (
  `user_id` INT NOT NULL,
  INDEX `fk_user_secrets_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_secrets_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `play_my_beat`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `play_my_beat`.`spotify_secrets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `play_my_beat`.`spotify_secrets` (
  `user_id` INT NOT NULL,
  `client_id` VARCHAR(45) NULL,
  `client_secret` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  INDEX `fk_spotify_secrets_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_spotify_secrets_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `play_my_beat`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
